config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  get '/articles', to: 'articles#index', as: :index

  get '/articles/new', to: 'articles#new', as: :new_article
  post '/articles', to: 'articles#create'

  #get '/articles/upvote', to: 'articles#index'

  get '/articles/:id', to: 'articles#show', as: :article

  get '/articles/:id/edit', to: 'articles#edit', as: :edit_article
  patch '/articles/:id', to: 'articles#update'

  delete '/articles/:id', to: 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(score: :desc)

    if params[:vote] == 'up'
      @article = Article.find(params[:article])
      @article.score += 1
      @article.save
    end

    if params[:vote] == 'down'
      @article = Article.find(params[:article])
      @article.score -= 1
      @article.save
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <h3>Title:</h3> <%= f.text_field :title %><br><br>
  <h3>Content:</h3> <%= f.text_area :content %><br><br>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<div class="top-nav">
  <h1><%= link_to "Wikinimous", index_path %></h1>
  <h3><%= link_to 'New article', new_article_path %></h3>
</div>

<div class="article-container" style="margin-top: 60px;">
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="article-container">

  <% @articles.each do |article| %>
    <div class="article-card">

      <div class="article-score">
        <%= link_to "▲", { controller: "articles", action: "index", article: article.id, vote: "up" }, class: "upvote" %>
        <span class="score"><%= article.score.to_s %></span>
        <%= link_to "▼", { controller: "articles", action: "index", article: article.id, vote: "down" }, class: "downvote" %>
      </div>

      <%= link_to article_path(article.id) do %>
        <h4><%= article.title %></h4>
        <p><%= article.content[0..520] %></p>
      <% end %>
    </div>
  <% end %>

</div>

app/views/articles/new.html.erb
<div class="form-container" style="margin-top: 60px;">
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="show-container">
  <div class="show-content">
    <h2>
      <%= @article.title %>
      <span style="float: right;">
        <%= link_to edit_article_path(@article.id) do %>
          <i class="fa-solid fa-pen-to-square"></i>pen
        <% end %>
        <%= link_to image_tag('trash-alt-solid.svg', size: '20'), article_path(@article), method: :delete, data: { confirm: "Are you sure?" }  %>
      </span>
    </h2>
    <p><%= @article.content %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> -->

  </head>

  <body>
  <div class="top-nav">
    <h1><%= link_to "Wikinimous", index_path %></h1>
    <h3><%= link_to 'New article', new_article_path %></h3>
  </div>
    <%= yield %>
  </body>
</html>